- name: Install Apache and php package
  tags: apache,apache2,httpd,centos,ubuntu
  package:
    name:
      - "{{ apache_pkg_name }}"
      - "{{ php_pkg_name }}"
    state: latest
    update_cache: yes
  
- name: clone git repo
  git:
    repo:
      - "{{ git_repo }}"
    dest: /var/www/html
    update: yes
  tags: apache,apache2,httpd,centos,ubuntu
  