---
- hosts: all
  become: true
  tasks:
    - name: Install Apache and php
      tags: apache,apache2,httpd,centos,ubuntu
      package:
        name:
          - "{{ apache_pkg }}"
          - "{{ php_pkg }}"
        state: present
        update_cache: yes
    

    

         
    # - name: Start httpd service
    #   service:
    #     name: httpd
    #     state: started
    #   when: ansible_distribution == 'CentOS'

    # - name: enable 80/tcp port
    #   firewalld:
    #     port: 80/tcp
    #     permanent: true
    #     state: enabled
    #   when: ansible_distribution == 'CentOS'
