---
- name: Install LAMP stack
  hosts: slave
  become: true
  tasks:
    - name: Copy bash script to Slave node
      copy:
        src: /home/vagrant/LAMP_install.sh
        dest: /home/vagrant/LAMP_install.sh
        mode: 0755

    - name: Execute bash script to setup LAMP stack
      command: /home/vagrant/LAMP_install.sh

    - name: Create cron job
      cron:
        name: "uptime check"
        minute: "0"
        hour: "0"
        job: "/usr/bin/uptime >> /home/vagrant/uptime.log"
    
    - name: Verify PHP application accessibility 
      shell: "curl http://192.168.33.12/var/www/laravel"
      register: result 
      ignore_errors: true

    - name: Show output debug
      debug:
      var: result.stdout
        
